(GH-130) Add  documentation
puppetlabs/prm pull request #158
Opened 2022-05-03 11:35 UTC by petergmurphy

2022-05-04 10:01 UTC, david22swan requested changes
Overall good and look's to cover everything needed in a clear and concise fashion.
Jut a few syntax errors, with the alert's not coming through correctly.

2022-05-04 10:01 UTC, david22swan commented on docs/md/content/usage/validate.md
> +{{% /alert %}}
same again

2022-05-04 10:47 UTC, petergmurphy commented on docs/md/content/usage/validate.md
> +{{% alert title="Note" color="primary" %}}
So the alerts will come through on documentation site looking like [this](https://www.docsy.dev/docs/adding-content/shortcodes/#alert); only the colour, heading and body will be different.

2022-05-04 10:49 UTC, petergmurphy commented on docs/md/content/usage/validate.md
> +{{% alert title="Note" color="primary" %}}
The docs site can be run locally by running the `docs.sh` script in the root dir of PRM.

2022-05-04 12:19 UTC, chelnak requested changes
Looks great! nice job.

I've left a few comments for consideration.

2022-05-04 12:19 UTC, chelnak commented on docs/md/content/usage/validate.md
> +It is very easy to run single tool validation with PRM. The command below shows an
```suggestion
It is very easy to validate with a single tool. The command below shows an
```

2022-05-04 12:19 UTC, chelnak commented on docs/md/content/usage/validate.md
> +outline of the core args and flags necessary for content validation:
```suggestion
outline of the core arguments and flags necessary for content validation:
```

2022-05-04 12:19 UTC, chelnak commented on docs/md/content/usage/validate.md
> +Example of a command composed to validate `epp` content against the current directory,
```suggestion
Here is an example of a command composed to validate `epp` content against the current directory,
```

2022-05-04 12:19 UTC, chelnak commented on docs/md/content/usage/validate.md
> +args; the tool args in this case will instruct epp to validate content in the specified directories.
```suggestion
arguments. The tool arguments in this case will instruct `epp` to validate content in the specified directories.
```

2022-05-04 12:19 UTC, chelnak commented on docs/md/content/usage/validate.md
> +
Maybe explain here why it can be useful to have a validate.yml file

2022-05-04 12:19 UTC, chelnak commented on docs/md/content/usage/validate.md
> +
Could be nice to have an some sort of heading here

2022-05-05 12:27 UTC, chelnak approved these changes

2022-05-05 12:29 UTC, merged