Gh 15/main/prm set get backend
puppetlabs/prm pull request #32
Opened 2021-11-16 18:26 UTC by sanfrancrisko

This PR is made up of multiple commits that:

- Implement the `prm set backend` command
- Fixes an issue with the `.prm.yml` not being instantiated by Viper (#30)
- Generates sensible default values for the Puppet Runtime and Backend, if not set

The `prm get` commands will need more thorough test coverage, which has been ticketed: #28 

Resolves: #15 , #30

2021-11-19 10:50 UTC, da-ar requested changes
I'm seeing issues with the cli not creating the config file:

![Screenshot 2021-11-19 104215](https://user-images.githubusercontent.com/1346683/142609739-d335936a-3596-4cbe-b1f3-f117f3a2c1a0.png)

2021-11-19 10:54 UTC, sanfrancrisko commented
> I'm seeing issues with the cli not creating the config file:
> 
> ![Screenshot 2021-11-19 104215](https://user-images.githubusercontent.com/1346683/142609739-d335936a-3596-4cbe-b1f3-f117f3a2c1a0.png)

Yikes...OK, I'll look in to that, cheers @da-ar . Good thing I'm working on #28 soon

2021-11-19 13:40 UTC, sanfrancrisko commented
Thanks for the catch @da-ar - needed to create the `.config` dir, if it doesn't exist already, but given my local system already had this, I didn't catch it.

Again, highlighting the need to get these acceptance tests running, sooner rather than later.

Should be fixed now 🤞

2021-11-24 17:37 UTC, da-ar commented on cmd/set/backend.go
> +		RunE:    sc.setBackendType,
```suggestion
		RunE:    sc.setBackendType,
		ValidArgs: []string{string(prm.DOCKER)},
```

Also add to the help text the list of valid options.

2021-11-30 15:47 UTC, merged